name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout_main
      uses: actions/checkout@v2
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail; ./default.configure; make; sudo make install-strip

    - name: build_pistop
      run: cd main; ./default.configure; make
