name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkoutmain
      uses: actions/checkout@v2
      with:
        path: main

    - name: checkoutqmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: qmail
      run: cd libqmail;./default.configure; make; make install-strip

    - name: configure
      run: ./default.configure
    - name: make
      run: make
