name: pistop C/C++ CI

on:
  push:
    paths:
      - '**'
      - .github/workflows/pistop-c-cpp.yml
      - '!**/debian/*'
      - '!**/pistop.spec.in'
      - '!**/obs/*'
      - '!**/doc/*'
      - '!**.md'
      - '!**/pistop-obs.yml'
      - '!example_config/*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout_main
      uses: actions/checkout@v4
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v4
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail; ./default.configure; make; sudo make install-strip

    - name: build_pistop
      run: |
        cd main; ./default.configure; make
        make clean; /bin/rm -rf .git ../libqmail autom4te.cache
        make -C debian;make pistop.spec

    - uses: actions/upload-artifact@v4
      with:
        name: pistop
        path: ${{ github.workspace }}
